# Render deployment configuration
# Render部署配置

# Service type
# 服务类型
type: web

# Build command
# 构建命令
buildCommand: npm run build

# Start command  
# 启动命令
startCommand: npm start

# Node.js version
# Node.js版本
nodeVersion: 18

# Environment
# 环境变量
envVars:
  - key: NODE_ENV
    value: production
